export const options = [
    
    'Story: The Red War',
    'Story: Curse of Osiris',
    'Story: Warmind',
    'Story: Forsaken',
    'Story: Shadowkeep',
    'Story: Beyond Light',
    'Bounties',
    
    'Raid: Garden of Salvation - Normal',
    'Raid: Garden of Salvation - Prestige',
    'Raid: The Last Wish',
    'Raid: Deep Stone Crypt',

    'Empire Hunts',
    'Wrathborn Hunts',
    'Battlegrounds',

    'Vanguard Strikes',
    'Nightmare Hunt - Legend',
    'Nightmare Hunt - Master', 
    'Nightfall The Ordeal', 
    'Nightfall The Ordeal - Legend', 
    'Nightfall The Ordeal - Master', 
    'Nightfall The Ordeal - Grandmaster', 

    'Crucible: Clash',
    'Crucible: Control',
    'Crucible: Elimination',
    'Crucible: Mayham Clash',
    'Crucible: Rotator Modes',
    'Crucible: Survival', 
    'Crucible: Iron Banner',
    'Crucible: Trials of Osiris',
    'Crucible: Private Match', 

    'Gambit',
    'Gambit: Private Match',

    'Patrol: Europa',
    'Patrol: Nessus',
    'Patrol: Moon',
    'Patrol: Dreaming City',
    'Patrol: Tangled Shore',
    'Patrol: Cosmodrome',
    'Patrol: EDZ',
    'Moon: Altars of Sorrow',
    'Public Activity: Europa Events',
    'Public Activity: Blind Well', 
    'Public Activity: Adventures', 
    'Public Activity: Lost Sector',
    'Public Activity: Public Events',

    'Dungeon: Pit of Hersey', 
    'Dungeon: Shattered Throne', 
    'Dungeon: Prophecy', 

    'Exotic Quest: Dead Mans Tale',
    'Exotic Quest: Cloudstrike',
    'Exotic Quest: Hawkmoon',
    'Exotic Quest: The Lament',
    'Exotic Quest: Salvations Drip',
    'Exotic Quest: Bastion',
    'Exotic Quest: Deatbringer',
    'Exotic Quest: Devils Ruin',
    'Exotic Quest: Divine Fragmentation',
    'Exotic Quest: Leviathans Breath',
    'Exotic Quest: Malfeasance',
    'Exotic Quest: Xenophage',
    'Exotic Quest: Ruinous Effigy',
    'Exotic Quest: Thorn',
    'Exotic Quest: Last Word',
    'Exotic Quest: Chaperone',
    
    'Exotic Mission: Presage',
    'Exotic Mission: The Whisper Normal',
    'Exotic Mission: The Whisper Heroic',
    'Exotic Mission: Outbreak Perfected Normal',
    'Exotic Mission: Outbreak Perfected Heroic'

]